/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Welcome message
         * @description Return a friendly welcome message.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WelcomeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate user and set refresh token cookie.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccessToken"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify email
         * @description Verify a newly registered user email with a one-time token.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VerifyEmailInput"];
                };
            };
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend verification email
         * @description Send a fresh verification email when the account still needs email confirmation.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResendVerificationInput"];
                };
            };
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Refresh access token
         * @description Rotate refresh token cookie and return a new access token.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccessToken"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Clear refresh token cookie and invalidate session.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Return the authenticated user profile.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description Return all users.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UsersResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create user
         * @description Create a new user account.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserCreateInput"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user by id
         * @description Return a single user by id. Requires authentication.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete user
         * @description Delete a user by id. Requires authentication.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create test user
         * @description Create a test user and seed sample transactions. Requires authentication.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TestUserCreateInput"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TestUserCreateResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List accounts
         * @description Return all accounts for the authenticated user.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NamedResourcesResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create account
         * @description Create a new account for the authenticated user.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NamedResourceInput"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NamedResourceResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List favorite accounts
         * @description Return all favorite accounts for the authenticated user.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NamedResourcesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get account by id
         * @description Return a single account by id.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NamedResourceResponse"];
                    };
                };
            };
        };
        /**
         * Update account
         * @description Update an account by id.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NamedResourceInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NamedResourceResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete account
         * @description Delete an account by id.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            acknowledged: boolean;
                            deletedCount: number;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{id}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Favorite account
         * @description Mark account as favorite for the authenticated user.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NamedResourceResponse"];
                    };
                };
            };
        };
        /**
         * Unfavorite account
         * @description Remove account from favorites for the authenticated user.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            acknowledged: boolean;
                            deletedCount: number;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List categories
         * @description Return all categories for the authenticated user.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NamedResourcesResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create category
         * @description Create a new category for the authenticated user.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NamedResourceInput"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NamedResourceResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List favorite categories
         * @description Return all favorite categories for the authenticated user.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NamedResourcesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get category by id
         * @description Return a single category by id.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NamedResourceResponse"];
                    };
                };
            };
        };
        /**
         * Update category
         * @description Update a category by id.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NamedResourceInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NamedResourceResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete category
         * @description Delete a category by id.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            acknowledged: boolean;
                            deletedCount: number;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{id}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Favorite category
         * @description Mark category as favorite for the authenticated user.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NamedResourceResponse"];
                    };
                };
            };
        };
        /**
         * Unfavorite category
         * @description Remove category from favorites for the authenticated user.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            acknowledged: boolean;
                            deletedCount: number;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paymentMethods/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List payment methods
         * @description Return all payment methods for the authenticated user.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NamedResourcesResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create payment method
         * @description Create a new payment method for the authenticated user.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NamedResourceInput"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NamedResourceResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paymentMethods/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List favorite payment methods
         * @description Return all favorite payment methods for the authenticated user.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NamedResourcesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paymentMethods/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get payment method by id
         * @description Return a single payment method by id.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NamedResourceResponse"];
                    };
                };
            };
        };
        /**
         * Update payment method
         * @description Update a payment method by id.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NamedResourceInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NamedResourceResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete payment method
         * @description Delete a payment method by id.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            acknowledged: boolean;
                            deletedCount: number;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paymentMethods/{id}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Favorite payment method
         * @description Mark payment method as favorite for the authenticated user.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NamedResourceResponse"];
                    };
                };
            };
        };
        /**
         * Unfavorite payment method
         * @description Remove payment method from favorites for the authenticated user.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            acknowledged: boolean;
                            deletedCount: number;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/currencies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List currencies
         * @description Return list of currencies with their codes and names.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            code: "USD" | "EUR" | "PLN" | "GBP" | "JPY" | "CHF" | "CAD" | "AUD" | "NZD" | "SEK" | "NOK" | "DKK" | "CZK" | "HUF" | "RON" | "BGN" | "TRY" | "UAH" | "INR" | "CNY" | "HKD" | "SGD" | "ZAR" | "BRL" | "MXN" | "ARS" | "CLP" | "COP" | "KRW" | "IDR" | "MYR" | "THB" | "AED" | "SAR" | "ILS" | "EGP";
                            name: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List transactions
         * @description Return paginated transactions for the authenticated user.
         */
        get: {
            parameters: {
                query?: {
                    categoryIds?: string;
                    paymentMethodIds?: string;
                    accountIds?: string;
                    excludeCategoryIds?: string;
                    excludePaymentMethodIds?: string;
                    excludeAccountIds?: string;
                    startDate?: unknown;
                    endDate?: unknown;
                    minAmount?: number;
                    maxAmount?: number;
                    transactionType?: "expense" | "income";
                    currency?: "USD" | "EUR" | "PLN" | "GBP" | "JPY" | "CHF" | "CAD" | "AUD" | "NZD" | "SEK" | "NOK" | "DKK" | "CZK" | "HUF" | "RON" | "BGN" | "TRY" | "UAH" | "INR" | "CNY" | "HKD" | "SGD" | "ZAR" | "BRL" | "MXN" | "ARS" | "CLP" | "COP" | "KRW" | "IDR" | "MYR" | "THB" | "AED" | "SAR" | "ILS" | "EGP";
                    page?: number;
                    limit?: number;
                    sortBy?: "date" | "amount";
                    sortOrder?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            page: number;
                            limit: number;
                            total: number;
                            totalPages: number;
                            items: components["schemas"]["TransactionsResponse"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Move all transactions to trash
         * @description Move all active transactions for the authenticated user to trash.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            acknowledged: boolean;
                            matchedCount: number;
                            modifiedCount: number;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/trash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List trashed transactions
         * @description Return paginated trashed transactions for the authenticated user.
         */
        get: {
            parameters: {
                query?: {
                    categoryIds?: string;
                    paymentMethodIds?: string;
                    accountIds?: string;
                    excludeCategoryIds?: string;
                    excludePaymentMethodIds?: string;
                    excludeAccountIds?: string;
                    startDate?: unknown;
                    endDate?: unknown;
                    minAmount?: number;
                    maxAmount?: number;
                    transactionType?: "expense" | "income";
                    currency?: "USD" | "EUR" | "PLN" | "GBP" | "JPY" | "CHF" | "CAD" | "AUD" | "NZD" | "SEK" | "NOK" | "DKK" | "CZK" | "HUF" | "RON" | "BGN" | "TRY" | "UAH" | "INR" | "CNY" | "HKD" | "SGD" | "ZAR" | "BRL" | "MXN" | "ARS" | "CLP" | "COP" | "KRW" | "IDR" | "MYR" | "THB" | "AED" | "SAR" | "ILS" | "EGP";
                    page?: number;
                    limit?: number;
                    sortBy?: "deletedAt" | "purgeAt" | "date" | "amount";
                    sortOrder?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            page: number;
                            limit: number;
                            total: number;
                            totalPages: number;
                            items: components["schemas"]["TrashedTransactionsResponse"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Empty trash
         * @description Permanently delete all trashed transactions for the authenticated user.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            acknowledged: boolean;
                            deletedCount: number;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export transactions
         * @description Export filtered transactions to CSV. Pagination parameters are accepted but ignored.
         */
        get: {
            parameters: {
                query?: {
                    categoryIds?: string;
                    paymentMethodIds?: string;
                    accountIds?: string;
                    excludeCategoryIds?: string;
                    excludePaymentMethodIds?: string;
                    excludeAccountIds?: string;
                    startDate?: unknown;
                    endDate?: unknown;
                    minAmount?: number;
                    maxAmount?: number;
                    transactionType?: "expense" | "income";
                    currency?: "USD" | "EUR" | "PLN" | "GBP" | "JPY" | "CHF" | "CAD" | "AUD" | "NZD" | "SEK" | "NOK" | "DKK" | "CZK" | "HUF" | "RON" | "BGN" | "TRY" | "UAH" | "INR" | "CNY" | "HKD" | "SGD" | "ZAR" | "BRL" | "MXN" | "ARS" | "CLP" | "COP" | "KRW" | "IDR" | "MYR" | "THB" | "AED" | "SAR" | "ILS" | "EGP";
                    page?: number;
                    limit?: number;
                    sortBy?: "date" | "amount";
                    sortOrder?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/totals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get transaction totals
         * @description Return totals grouped by currency and transaction type.
         */
        get: {
            parameters: {
                query?: {
                    categoryIds?: string;
                    paymentMethodIds?: string;
                    accountIds?: string;
                    excludeCategoryIds?: string;
                    excludePaymentMethodIds?: string;
                    excludeAccountIds?: string;
                    startDate?: unknown;
                    endDate?: unknown;
                    minAmount?: number;
                    maxAmount?: number;
                    transactionType?: "expense" | "income";
                    currency?: "USD" | "EUR" | "PLN" | "GBP" | "JPY" | "CHF" | "CAD" | "AUD" | "NZD" | "SEK" | "NOK" | "DKK" | "CZK" | "HUF" | "RON" | "BGN" | "TRY" | "UAH" | "INR" | "CNY" | "HKD" | "SGD" | "ZAR" | "BRL" | "MXN" | "ARS" | "CLP" | "COP" | "KRW" | "IDR" | "MYR" | "THB" | "AED" | "SAR" | "ILS" | "EGP";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            byCurrency: {
                                [key: string]: {
                                    totalItems: number;
                                    expense: {
                                        totalAmount: number;
                                        totalItems: number;
                                        averageAmount: number;
                                        maxAmount: number;
                                        minAmount: number;
                                    };
                                    income: {
                                        totalAmount: number;
                                        totalItems: number;
                                        averageAmount: number;
                                        maxAmount: number;
                                        minAmount: number;
                                    };
                                };
                            };
                            overall: {
                                totalItems: number;
                                expense: {
                                    totalItems: number;
                                };
                                income: {
                                    totalItems: number;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/statistics/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get account balance statistics
         * @description Return transaction balances grouped by account and currency.
         */
        get: {
            parameters: {
                query: {
                    startDate?: unknown;
                    endDate?: unknown;
                    transactionType?: "expense" | "income";
                    currency?: "USD" | "EUR" | "PLN" | "GBP" | "JPY" | "CHF" | "CAD" | "AUD" | "NZD" | "SEK" | "NOK" | "DKK" | "CZK" | "HUF" | "RON" | "BGN" | "TRY" | "UAH" | "INR" | "CNY" | "HKD" | "SGD" | "ZAR" | "BRL" | "MXN" | "ARS" | "CLP" | "COP" | "KRW" | "IDR" | "MYR" | "THB" | "AED" | "SAR" | "ILS" | "EGP";
                    baseCurrency: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            currencies: {
                                currency: string;
                                totalAmount: number;
                                totalItems: number;
                                normalizedTotalAmount?: number;
                                accounts: {
                                    accountId: string;
                                    accountName: string;
                                    /** @enum {string} */
                                    accountType: "user" | "system";
                                    totalAmount: number;
                                    totalItems: number;
                                    normalizedTotalAmount?: number;
                                }[];
                            }[];
                            normalizedBaseCurrency?: string;
                            normalizedTotalAmount?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get transaction statistics
         * @description Return statistics grouped by time period.
         */
        get: {
            parameters: {
                query: {
                    categoryIds?: string;
                    paymentMethodIds?: string;
                    accountIds?: string;
                    excludeCategoryIds?: string;
                    excludePaymentMethodIds?: string;
                    excludeAccountIds?: string;
                    year?: number;
                    month?: number;
                    transactionType: "expense" | "income";
                    currency: "USD" | "EUR" | "PLN" | "GBP" | "JPY" | "CHF" | "CAD" | "AUD" | "NZD" | "SEK" | "NOK" | "DKK" | "CZK" | "HUF" | "RON" | "BGN" | "TRY" | "UAH" | "INR" | "CNY" | "HKD" | "SGD" | "ZAR" | "BRL" | "MXN" | "ARS" | "CLP" | "COP" | "KRW" | "IDR" | "MYR" | "THB" | "AED" | "SAR" | "ILS" | "EGP";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            totalAmount: number;
                            totalItems: number;
                        } | {
                            allTime: {
                                totalAmount: number;
                                totalItems: number;
                            };
                            monthly: {
                                [key: string]: {
                                    totalAmount: number;
                                    totalItems: number;
                                };
                            };
                        } | {
                            allTime: {
                                totalAmount: number;
                                totalItems: number;
                            };
                            yearly: {
                                [key: string]: {
                                    totalAmount: number;
                                    totalItems: number;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/trash/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get trashed transaction by id
         * @description Return a single trashed transaction by id.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrashedTransactionDetailsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete trashed transaction permanently
         * @description Permanently delete a trashed transaction by id. Linked transaction is deleted as well.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            acknowledged: boolean;
                            deletedCount: number;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/trash/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore trashed transaction
         * @description Restore a trashed transaction by id. Linked transaction is restored as well.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            acknowledged: boolean;
                            matchedCount: number;
                            modifiedCount: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/trash/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore all trashed transactions
         * @description Restore all trashed transactions for the authenticated user.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            acknowledged: boolean;
                            matchedCount: number;
                            modifiedCount: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get transaction by id
         * @description Return a single transaction by id.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionDetailsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete transaction
         * @description Move a transaction to trash by id.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            acknowledged: boolean;
                            matchedCount: number;
                            modifiedCount: number;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/standard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create standard transaction
         * @description Create a standard transaction.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransactionStandardInput"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create transactions in bulk
         * @description Create multiple transactions at once. Standard transactions create one entry, exchange and transfer transactions create linked pairs.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransactionBulkCreateInput"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionsResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create exchange transaction
         * @description Create an exchange transaction (two linked entries).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransactionExchangeInput"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionResponse"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/transfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create transfer transaction
         * @description Create a transfer transaction (two linked entries).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransactionTransferInput"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionResponse"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/standard/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update standard transaction
         * @description Update a standard transaction by id.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransactionStandardInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/transfer/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update transfer transaction
         * @description Update a transfer transaction by id.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransactionTransferInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionResponse"][];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/exchange/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update exchange transaction
         * @description Update an exchange transaction by id.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransactionExchangeInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionResponse"][];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create test transactions
         * @description Create test transactions for the authenticated user (only if none exist).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TestTransactionsCreateInput"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TestTransactionsCreateResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        WelcomeResponseInput: {
            message: string;
        };
        NamedResourceInput: {
            name: string;
        };
        NamedResourceResponseInput: {
            name: string;
            id: string;
            ownerId?: string;
            /** @enum {string} */
            type: "user" | "system";
            nameNormalized: string;
            isFavorite: boolean;
        };
        NamedResourcesResponseInput: components["schemas"]["NamedResourceResponseInput"][];
        LoginInput: {
            /** Format: email */
            email: string;
            password: string;
        };
        ResendVerificationInput: {
            /** Format: email */
            email: string;
        };
        VerifyEmailInput: {
            token: string;
        };
        AccessTokenInput: {
            accessToken: string;
        };
        UsersResponseInput: components["schemas"]["UserResponseInput"][];
        UserResponseInput: {
            firstName: string;
            lastName: string;
            /** Format: email */
            email: string;
            id: string;
            emailVerifiedAt: unknown | null;
            emailVerificationMethod: ("legacy-backfill" | "self-verified") | null;
            createdAt: unknown;
            updatedAt: unknown;
        };
        UserCreateInput: {
            firstName: string;
            lastName: string;
            /** Format: email */
            email: string;
            password: string;
        };
        TestUserCreateInput: {
            username: string;
            totalTransactions?: number;
        };
        TestUserCreateResponseInput: {
            userId: string;
            /** Format: email */
            email: string;
            insertedTransactionsCount: number;
        };
        TransactionStandardInput: {
            date: unknown;
            description: string;
            amount: number;
            /** @enum {string} */
            currency: "USD" | "EUR" | "PLN" | "GBP" | "JPY" | "CHF" | "CAD" | "AUD" | "NZD" | "SEK" | "NOK" | "DKK" | "CZK" | "HUF" | "RON" | "BGN" | "TRY" | "UAH" | "INR" | "CNY" | "HKD" | "SGD" | "ZAR" | "BRL" | "MXN" | "ARS" | "CLP" | "COP" | "KRW" | "IDR" | "MYR" | "THB" | "AED" | "SAR" | "ILS" | "EGP";
            categoryId?: string | null;
            paymentMethodId?: string | null;
            accountId?: string | null;
            /** @enum {string} */
            transactionType: "expense" | "income";
        };
        TransactionExchangeInput: {
            date: unknown;
            description: string;
            amountExpense: number;
            amountIncome: number;
            /** @enum {string} */
            currencyExpense: "USD" | "EUR" | "PLN" | "GBP" | "JPY" | "CHF" | "CAD" | "AUD" | "NZD" | "SEK" | "NOK" | "DKK" | "CZK" | "HUF" | "RON" | "BGN" | "TRY" | "UAH" | "INR" | "CNY" | "HKD" | "SGD" | "ZAR" | "BRL" | "MXN" | "ARS" | "CLP" | "COP" | "KRW" | "IDR" | "MYR" | "THB" | "AED" | "SAR" | "ILS" | "EGP";
            /** @enum {string} */
            currencyIncome: "USD" | "EUR" | "PLN" | "GBP" | "JPY" | "CHF" | "CAD" | "AUD" | "NZD" | "SEK" | "NOK" | "DKK" | "CZK" | "HUF" | "RON" | "BGN" | "TRY" | "UAH" | "INR" | "CNY" | "HKD" | "SGD" | "ZAR" | "BRL" | "MXN" | "ARS" | "CLP" | "COP" | "KRW" | "IDR" | "MYR" | "THB" | "AED" | "SAR" | "ILS" | "EGP";
            accountExpenseId?: string | null;
            accountIncomeId?: string | null;
            paymentMethodId?: string | null;
        };
        TransactionTransferInput: {
            date: unknown;
            description: string;
            amount: number;
            /** @enum {string} */
            currency: "USD" | "EUR" | "PLN" | "GBP" | "JPY" | "CHF" | "CAD" | "AUD" | "NZD" | "SEK" | "NOK" | "DKK" | "CZK" | "HUF" | "RON" | "BGN" | "TRY" | "UAH" | "INR" | "CNY" | "HKD" | "SGD" | "ZAR" | "BRL" | "MXN" | "ARS" | "CLP" | "COP" | "KRW" | "IDR" | "MYR" | "THB" | "AED" | "SAR" | "ILS" | "EGP";
            accountExpenseId?: string | null;
            accountIncomeId?: string | null;
            paymentMethodId?: string | null;
        };
        TransactionCreateBulkItemInput: unknown;
        TransactionBulkCreateInput: {
            transactions: components["schemas"]["TransactionCreateBulkItemInput"][];
        };
        TransactionResponseInput: {
            date: unknown;
            description: string;
            amount: number;
            /** @enum {string} */
            currency: "USD" | "EUR" | "PLN" | "GBP" | "JPY" | "CHF" | "CAD" | "AUD" | "NZD" | "SEK" | "NOK" | "DKK" | "CZK" | "HUF" | "RON" | "BGN" | "TRY" | "UAH" | "INR" | "CNY" | "HKD" | "SGD" | "ZAR" | "BRL" | "MXN" | "ARS" | "CLP" | "COP" | "KRW" | "IDR" | "MYR" | "THB" | "AED" | "SAR" | "ILS" | "EGP";
            /** @enum {string} */
            transactionType: "expense" | "income";
            id: string;
            ownerId: string;
            createdAt: unknown;
            updatedAt: unknown;
            sourceIndex: number;
            sourceRefIndex?: number;
            refId?: string;
            currencies?: string;
            exchangeRate?: number;
            category: {
                id: string;
                /** @enum {string} */
                type: "user" | "system";
                name: string;
            };
            paymentMethod: {
                id: string;
                /** @enum {string} */
                type: "user" | "system";
                name: string;
            };
            account: {
                id: string;
                /** @enum {string} */
                type: "user" | "system";
                name: string;
            };
        };
        TransactionDetailsResponseInput: {
            date: unknown;
            description: string;
            amount: number;
            /** @enum {string} */
            currency: "USD" | "EUR" | "PLN" | "GBP" | "JPY" | "CHF" | "CAD" | "AUD" | "NZD" | "SEK" | "NOK" | "DKK" | "CZK" | "HUF" | "RON" | "BGN" | "TRY" | "UAH" | "INR" | "CNY" | "HKD" | "SGD" | "ZAR" | "BRL" | "MXN" | "ARS" | "CLP" | "COP" | "KRW" | "IDR" | "MYR" | "THB" | "AED" | "SAR" | "ILS" | "EGP";
            /** @enum {string} */
            transactionType: "expense" | "income";
            id: string;
            ownerId: string;
            createdAt: unknown;
            updatedAt: unknown;
            sourceIndex: number;
            sourceRefIndex?: number;
            refId?: string;
            currencies?: string;
            exchangeRate?: number;
            category: {
                id: string;
                /** @enum {string} */
                type: "user" | "system";
                name: string;
            };
            paymentMethod: {
                id: string;
                /** @enum {string} */
                type: "user" | "system";
                name: string;
            };
            account: {
                id: string;
                /** @enum {string} */
                type: "user" | "system";
                name: string;
            };
            reference?: components["schemas"]["TransactionResponseInput"];
        };
        TransactionDeletionInput: {
            deletedAt: unknown;
            purgeAt: unknown;
        };
        TrashedTransactionResponseInput: {
            date: unknown;
            description: string;
            amount: number;
            /** @enum {string} */
            currency: "USD" | "EUR" | "PLN" | "GBP" | "JPY" | "CHF" | "CAD" | "AUD" | "NZD" | "SEK" | "NOK" | "DKK" | "CZK" | "HUF" | "RON" | "BGN" | "TRY" | "UAH" | "INR" | "CNY" | "HKD" | "SGD" | "ZAR" | "BRL" | "MXN" | "ARS" | "CLP" | "COP" | "KRW" | "IDR" | "MYR" | "THB" | "AED" | "SAR" | "ILS" | "EGP";
            /** @enum {string} */
            transactionType: "expense" | "income";
            id: string;
            ownerId: string;
            createdAt: unknown;
            updatedAt: unknown;
            sourceIndex: number;
            sourceRefIndex?: number;
            refId?: string;
            currencies?: string;
            exchangeRate?: number;
            category: {
                id: string;
                /** @enum {string} */
                type: "user" | "system";
                name: string;
            };
            paymentMethod: {
                id: string;
                /** @enum {string} */
                type: "user" | "system";
                name: string;
            };
            account: {
                id: string;
                /** @enum {string} */
                type: "user" | "system";
                name: string;
            };
            deletion: components["schemas"]["TransactionDeletionInput"];
        };
        TrashedTransactionDetailsResponseInput: {
            date: unknown;
            description: string;
            amount: number;
            /** @enum {string} */
            currency: "USD" | "EUR" | "PLN" | "GBP" | "JPY" | "CHF" | "CAD" | "AUD" | "NZD" | "SEK" | "NOK" | "DKK" | "CZK" | "HUF" | "RON" | "BGN" | "TRY" | "UAH" | "INR" | "CNY" | "HKD" | "SGD" | "ZAR" | "BRL" | "MXN" | "ARS" | "CLP" | "COP" | "KRW" | "IDR" | "MYR" | "THB" | "AED" | "SAR" | "ILS" | "EGP";
            /** @enum {string} */
            transactionType: "expense" | "income";
            id: string;
            ownerId: string;
            createdAt: unknown;
            updatedAt: unknown;
            sourceIndex: number;
            sourceRefIndex?: number;
            refId?: string;
            currencies?: string;
            exchangeRate?: number;
            category: {
                id: string;
                /** @enum {string} */
                type: "user" | "system";
                name: string;
            };
            paymentMethod: {
                id: string;
                /** @enum {string} */
                type: "user" | "system";
                name: string;
            };
            account: {
                id: string;
                /** @enum {string} */
                type: "user" | "system";
                name: string;
            };
            deletion: components["schemas"]["TransactionDeletionInput"];
            reference?: components["schemas"]["TrashedTransactionResponseInput"];
        };
        TransactionsResponseInput: components["schemas"]["TransactionResponseInput"][];
        TrashedTransactionsResponseInput: components["schemas"]["TrashedTransactionResponseInput"][];
        TestTransactionsCreateInput: {
            totalTransactions: number;
        };
        TestTransactionsCreateResponseInput: {
            insertedCount: number;
        };
        WelcomeResponse: {
            message: string;
        };
        NamedResource: {
            name: string;
        };
        NamedResourceResponse: {
            name: string;
            id: string;
            ownerId?: string;
            /** @enum {string} */
            type: "user" | "system";
            nameNormalized: string;
            isFavorite: boolean;
        };
        NamedResourcesResponse: components["schemas"]["NamedResourceResponse"][];
        Login: {
            /** Format: email */
            email: string;
            password: string;
        };
        ResendVerification: {
            /** Format: email */
            email: string;
        };
        VerifyEmail: {
            token: string;
        };
        AccessToken: {
            accessToken: string;
        };
        UsersResponse: components["schemas"]["UserResponse"][];
        UserResponse: {
            firstName: string;
            lastName: string;
            /** Format: email */
            email: string;
            id: string;
            emailVerifiedAt: string | null;
            emailVerificationMethod: ("legacy-backfill" | "self-verified") | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UserCreate: {
            firstName: string;
            lastName: string;
            /** Format: email */
            email: string;
            password: string;
        };
        TestUserCreate: {
            username: string;
            totalTransactions?: number;
        };
        TestUserCreateResponse: {
            userId: string;
            /** Format: email */
            email: string;
            insertedTransactionsCount: number;
        };
        TransactionStandard: {
            /** Format: date-time */
            date: string;
            description: string;
            amount: number;
            /** @enum {string} */
            currency: "USD" | "EUR" | "PLN" | "GBP" | "JPY" | "CHF" | "CAD" | "AUD" | "NZD" | "SEK" | "NOK" | "DKK" | "CZK" | "HUF" | "RON" | "BGN" | "TRY" | "UAH" | "INR" | "CNY" | "HKD" | "SGD" | "ZAR" | "BRL" | "MXN" | "ARS" | "CLP" | "COP" | "KRW" | "IDR" | "MYR" | "THB" | "AED" | "SAR" | "ILS" | "EGP";
            categoryId?: string | null;
            paymentMethodId?: string | null;
            accountId?: string | null;
            /** @enum {string} */
            transactionType: "expense" | "income";
        };
        TransactionExchange: {
            /** Format: date-time */
            date: string;
            description: string;
            amountExpense: number;
            amountIncome: number;
            /** @enum {string} */
            currencyExpense: "USD" | "EUR" | "PLN" | "GBP" | "JPY" | "CHF" | "CAD" | "AUD" | "NZD" | "SEK" | "NOK" | "DKK" | "CZK" | "HUF" | "RON" | "BGN" | "TRY" | "UAH" | "INR" | "CNY" | "HKD" | "SGD" | "ZAR" | "BRL" | "MXN" | "ARS" | "CLP" | "COP" | "KRW" | "IDR" | "MYR" | "THB" | "AED" | "SAR" | "ILS" | "EGP";
            /** @enum {string} */
            currencyIncome: "USD" | "EUR" | "PLN" | "GBP" | "JPY" | "CHF" | "CAD" | "AUD" | "NZD" | "SEK" | "NOK" | "DKK" | "CZK" | "HUF" | "RON" | "BGN" | "TRY" | "UAH" | "INR" | "CNY" | "HKD" | "SGD" | "ZAR" | "BRL" | "MXN" | "ARS" | "CLP" | "COP" | "KRW" | "IDR" | "MYR" | "THB" | "AED" | "SAR" | "ILS" | "EGP";
            accountExpenseId?: string | null;
            accountIncomeId?: string | null;
            paymentMethodId?: string | null;
        };
        TransactionTransfer: {
            /** Format: date-time */
            date: string;
            description: string;
            amount: number;
            /** @enum {string} */
            currency: "USD" | "EUR" | "PLN" | "GBP" | "JPY" | "CHF" | "CAD" | "AUD" | "NZD" | "SEK" | "NOK" | "DKK" | "CZK" | "HUF" | "RON" | "BGN" | "TRY" | "UAH" | "INR" | "CNY" | "HKD" | "SGD" | "ZAR" | "BRL" | "MXN" | "ARS" | "CLP" | "COP" | "KRW" | "IDR" | "MYR" | "THB" | "AED" | "SAR" | "ILS" | "EGP";
            accountExpenseId?: string | null;
            accountIncomeId?: string | null;
            paymentMethodId?: string | null;
        };
        TransactionCreateBulkItem: unknown;
        TransactionBulkCreate: {
            transactions: components["schemas"]["TransactionCreateBulkItem"][];
        };
        TransactionResponse: {
            /** Format: date-time */
            date: string;
            description: string;
            amount: number;
            /** @enum {string} */
            currency: "USD" | "EUR" | "PLN" | "GBP" | "JPY" | "CHF" | "CAD" | "AUD" | "NZD" | "SEK" | "NOK" | "DKK" | "CZK" | "HUF" | "RON" | "BGN" | "TRY" | "UAH" | "INR" | "CNY" | "HKD" | "SGD" | "ZAR" | "BRL" | "MXN" | "ARS" | "CLP" | "COP" | "KRW" | "IDR" | "MYR" | "THB" | "AED" | "SAR" | "ILS" | "EGP";
            /** @enum {string} */
            transactionType: "expense" | "income";
            id: string;
            ownerId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            sourceIndex: number;
            sourceRefIndex?: number;
            refId?: string;
            currencies?: string;
            exchangeRate?: number;
            category: {
                id: string;
                /** @enum {string} */
                type: "user" | "system";
                name: string;
            };
            paymentMethod: {
                id: string;
                /** @enum {string} */
                type: "user" | "system";
                name: string;
            };
            account: {
                id: string;
                /** @enum {string} */
                type: "user" | "system";
                name: string;
            };
        };
        TransactionDetailsResponse: {
            /** Format: date-time */
            date: string;
            description: string;
            amount: number;
            /** @enum {string} */
            currency: "USD" | "EUR" | "PLN" | "GBP" | "JPY" | "CHF" | "CAD" | "AUD" | "NZD" | "SEK" | "NOK" | "DKK" | "CZK" | "HUF" | "RON" | "BGN" | "TRY" | "UAH" | "INR" | "CNY" | "HKD" | "SGD" | "ZAR" | "BRL" | "MXN" | "ARS" | "CLP" | "COP" | "KRW" | "IDR" | "MYR" | "THB" | "AED" | "SAR" | "ILS" | "EGP";
            /** @enum {string} */
            transactionType: "expense" | "income";
            id: string;
            ownerId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            sourceIndex: number;
            sourceRefIndex?: number;
            refId?: string;
            currencies?: string;
            exchangeRate?: number;
            category: {
                id: string;
                /** @enum {string} */
                type: "user" | "system";
                name: string;
            };
            paymentMethod: {
                id: string;
                /** @enum {string} */
                type: "user" | "system";
                name: string;
            };
            account: {
                id: string;
                /** @enum {string} */
                type: "user" | "system";
                name: string;
            };
            reference?: components["schemas"]["TransactionResponse"];
        };
        TransactionDeletion: {
            /** Format: date-time */
            deletedAt: string;
            /** Format: date-time */
            purgeAt: string;
        };
        TrashedTransactionResponse: {
            /** Format: date-time */
            date: string;
            description: string;
            amount: number;
            /** @enum {string} */
            currency: "USD" | "EUR" | "PLN" | "GBP" | "JPY" | "CHF" | "CAD" | "AUD" | "NZD" | "SEK" | "NOK" | "DKK" | "CZK" | "HUF" | "RON" | "BGN" | "TRY" | "UAH" | "INR" | "CNY" | "HKD" | "SGD" | "ZAR" | "BRL" | "MXN" | "ARS" | "CLP" | "COP" | "KRW" | "IDR" | "MYR" | "THB" | "AED" | "SAR" | "ILS" | "EGP";
            /** @enum {string} */
            transactionType: "expense" | "income";
            id: string;
            ownerId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            sourceIndex: number;
            sourceRefIndex?: number;
            refId?: string;
            currencies?: string;
            exchangeRate?: number;
            category: {
                id: string;
                /** @enum {string} */
                type: "user" | "system";
                name: string;
            };
            paymentMethod: {
                id: string;
                /** @enum {string} */
                type: "user" | "system";
                name: string;
            };
            account: {
                id: string;
                /** @enum {string} */
                type: "user" | "system";
                name: string;
            };
            deletion: components["schemas"]["TransactionDeletion"];
        };
        TrashedTransactionDetailsResponse: {
            /** Format: date-time */
            date: string;
            description: string;
            amount: number;
            /** @enum {string} */
            currency: "USD" | "EUR" | "PLN" | "GBP" | "JPY" | "CHF" | "CAD" | "AUD" | "NZD" | "SEK" | "NOK" | "DKK" | "CZK" | "HUF" | "RON" | "BGN" | "TRY" | "UAH" | "INR" | "CNY" | "HKD" | "SGD" | "ZAR" | "BRL" | "MXN" | "ARS" | "CLP" | "COP" | "KRW" | "IDR" | "MYR" | "THB" | "AED" | "SAR" | "ILS" | "EGP";
            /** @enum {string} */
            transactionType: "expense" | "income";
            id: string;
            ownerId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            sourceIndex: number;
            sourceRefIndex?: number;
            refId?: string;
            currencies?: string;
            exchangeRate?: number;
            category: {
                id: string;
                /** @enum {string} */
                type: "user" | "system";
                name: string;
            };
            paymentMethod: {
                id: string;
                /** @enum {string} */
                type: "user" | "system";
                name: string;
            };
            account: {
                id: string;
                /** @enum {string} */
                type: "user" | "system";
                name: string;
            };
            deletion: components["schemas"]["TransactionDeletion"];
            reference?: components["schemas"]["TrashedTransactionResponse"];
        };
        TransactionsResponse: components["schemas"]["TransactionResponse"][];
        TrashedTransactionsResponse: components["schemas"]["TrashedTransactionResponse"][];
        TestTransactionsCreate: {
            totalTransactions: number;
        };
        TestTransactionsCreateResponse: {
            insertedCount: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
